### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gazpachu**
Fixed local state with real Y value

### CODE REVIEW

**Comment by jeremenichelli** [comment]
Oh good catch!

**Comment by gazpachu** [comment]
Even after fixing the % issue, it only works fine if I resize the window. Any idea of what could be wrong?

**Comment by jeremenichelli** [comment]
Weird, because when an observer is created it triggers a callback call, might be good debugging.

Do you mean that it only works on resize and not on scroll, or that initially it doesn't track the scroll until you resize one?

**Comment by gazpachu** [comment]
It does track the scroll at the beginning, but the values that Y gets are not from 0 to 1. They are from 0 to 0.875. If I slightly resize the window, then I start getting from 0 to 1.

**Comment by jeremenichelli** [comment]
Oh I see, that's because after the observer gets created something changes the height of the body somehow, it could be a font loading, an image. 

There are lots of ways to make sure this doesn't happen. You can listen to window's load event and then initialize the observer, defer the element rendering after resources have been loaded and inserted in the page, or call `observer._onResize()` but beware that is a private method and can be deprecated in minor updates.

**Comment by gazpachu** [comment]
Hmmm, I've delayed the creation of the observer until everything is loaded, but somehow is still not working. I'm not sure how to check the onResize event. Could you plz put an example?

```
componentWillReceiveProps(newProps) {
    if (newProps.item && !this.progressObserver) {
      this.progressObserver = new ScrollProgress((x, y) => {
        this.setState({ progress: y * 100 });
      });
    }
  }
```

It's a blog post component:

```
import React, { PureComponent } from 'react';
import Helmet from 'react-helmet';
import ScrollProgress from 'scrollprogress';
import Moment from 'moment';
import Customlink from '../common/lib/link/link';
import { APP_NAME } from '../../constants/constants';

class Post extends PureComponent {

  constructor(props) {
    super(props);

    this.state = {
      progress: 0
    };
  }

  componentWillReceiveProps(newProps) {
    if (newProps.item && !this.progressObserver) {
      this.progressObserver = new ScrollProgress((x, y) => {
        this.setState({ progress: y * 100 });
      });
    }
  }

  componentWillUnmount() {
    this.progressObserver.destroy();
  }

  render() {
    const { item } = this.props;
    const style = {
      backgroundColor: 'rebeccapurple',
      height: '5px',
      position: 'fixed',
      top: 0,
      left: 0,
      bottom: 0,
      width: `${this.state.progress}%`
    };

    return (
      <section className="post page">
        <div className="progress-bar" style={style} />
        {item ?
          <div>
            <h1 className="post-title">{item.title}</h1>
            <div className="post-meta">
              Created by {item.author.name} on {Moment(item.published_at).format('MMM D, YYYY')}
              <Customlink to={`/admin/${item.id}`} className="btn btn-primary align-right">Edit post</Customlink>
            </div>
            <img className="featured-image" src={item.feature_image} width="200" alt={item.title} />
            <div className="excerpt" dangerouslySetInnerHTML={{ __html: item.html }} />
            <Helmet title={`${item.title} | ${APP_NAME}`} />
          </div>
        : null}
      </section>
    );
  }
}

export default Post;
```

**Comment by jeremenichelli** [comment]
For your case, in any part of the component you would need to call `this.progressObserver._onResize()`, in either case, the ideal thing would be to track what is triggering a viewport metric change and render the element after that.

**Comment by gazpachu** [comment]
maybe it's the post image, which is quite big

**Comment by gazpachu** [comment]
Ok, so this fixed it:

```
import React, { Component } from 'react';
import Helmet from 'react-helmet';
import ScrollProgress from 'scrollprogress';
import Moment from 'moment';
import Customlink from '../common/lib/link/link';
import { APP_NAME } from '../../constants/constants';

class Post extends Component {

  constructor(props) {
    super(props);

    this.state = {
      progress: 0
    };

    this.handleImageLoaded = this.handleImageLoaded.bind(this);
  }

  componentWillReceiveProps(newProps) {
    this.setupProgressBar(newProps);
  }

  componentWillUnmount() {
    this.progressObserver.destroy();
  }

  setupProgressBar() {
    if (this.props.item && !this.progressObserver) {
      this.progressObserver = new ScrollProgress((x, y) => {
        this.setState({ progress: y * 100 });
      });
    }
  }

  handleImageLoaded() {
    this.setupProgressBar(this.props);
  }

  render() {
    const { item } = this.props;
    const style = {
      backgroundColor: 'rebeccapurple',
      height: '5px',
      position: 'fixed',
      top: 0,
      left: 0,
      bottom: 0,
      width: `${this.state.progress}%`
    };

    return (
      <section className="post page">
        <div className="progress-bar" style={style} />
        {item ?
          <div>
            <h1 className="post-title">{item.title}</h1>
            <div className="post-meta">
              Created by {item.author.name} on {Moment(item.published_at).format('MMM D, YYYY')}
              <Customlink to={`/admin/${item.id}`} className="btn btn-primary align-right">Edit post</Customlink>
            </div>
            <img className="featured-image" src={item.feature_image} width="200" alt={item.title} onLoad={this.handleImageLoaded} />
            <div className="excerpt" dangerouslySetInnerHTML={{ __html: item.html }} />
            <Helmet title={`${item.title} | ${APP_NAME}`} />
          </div>
        : null}
      </section>
    );
  }
}

export default Post;
```

**Comment by gazpachu** [comment]
Actually, it's not yet fixed :/ The code above works only for posts that only have one featured image, but not for posts that have several images in the content. So I'll have to figure out something to wait until all images are loaded

**Comment by jeremenichelli** [comment]
If this miscalculation is because of images loading async, my suggestion would be to put height and width of the images ahead of time.

**Comment by gazpachu** [comment]
I can't do that, the authors of the blog posts can load any images with any size or videos, embedded objects, etc. I'm trying to find a way to detect when all the assets have been loaded but it doesn't seem to be a trivial thing.

**Comment by jeremenichelli** [comment]
I don't know exactly how the site works, but if there's a backend receiving the content, you can get the image file size, calculate aspect ratio and later pass it to the component. But it's really hard to infer from here. 

If the posts are not loaded as a SPA, you can create a global promise with the window's load event and initialize the progress bar after that.

I wrote a post about how to do that: https://jeremenichelli.github.io/2016/04/patterns-for-a-promise-based-initialization/#dom-ready

**Comment by gazpachu** [comment]
Thanks,

After testing a few approaches, I think this is the easiest way:

```
componentDidMount() {
    window.onscroll = debounce(() => {
      if (this.progressObserver) {
        this.progressObserver._onResize();
      }
    }, 500);
  }
```

**Comment by jeremenichelli** [comment]
That could generate a critical hit in performance. Another solution is to export the observer outside the component and call the `_onResize` event from the onload function of the images.

**Pull request merged**
